const app=document.querySelector("#app");
const state={page:location.hash.slice(1)||"home",liked:{},progress:60,language:"Deutsch",level:"A2",lesson:0,theme:localStorage.theme||"light"};
const img="https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80";

function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(t){const x=document.querySelector("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
function go(p){state.page=p;location.hash=p;render()}
function nav(){document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll(".sidebar nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===state.page))}
function header(){document.querySelector("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.theme=document.body.classList.contains("dark")?"dark":"light"};document.querySelector("#bellBtn").onclick=()=>go("notifications");document.querySelector("#menuBtn").onclick=()=>toast("استخدم القائمة السفلية على الهاتف")}
function home(){return `<div class="card composer"><div class="avatar small">S</div><input id="composer" placeholder="ما الذي يدور في ذهنك؟"><button class="primary post-btn" id="publish">نشر</button></div>
<div class="card stories"><div class="story"><div class="avatar">+</div><b>إضافة قصة</b></div>${["Shahwan","Sara","Ali","Reem","Mohammed"].map((n,i)=>`<div class="story"><div class="avatar">${n[0]}</div><b>${n}</b></div>`).join("")}</div>
${post("p1","Shahwan Khalaf","يوم جميل في هامبورغ 🇩🇪❤️ من يريد ممارسة اللغة الألمانية معي؟")}
${post("p2","Sara Ahmed","Heute lernen wir zusammen Deutsch! 📚")}
<div class="hero"><h1>🎓 تعلم اللغات</h1><p>حوّل وقتك على الشبكة الاجتماعية إلى وقت مفيد.</p><button class="primary" onclick="go('learning')">ابدأ التعلم</button></div>`}
function post(id,name,text){return `<article class="card"><div class="post-head"><div class="avatar small">${name[0]}</div><div><b>${name}</b><small>منذ 3 ساعات · 🌐</small></div><button class="more">•••</button></div><p>${text}</p>${id==="p1"?`<img class="post-image" src="${img}" alt="Hamburg">`:""}<div class="post-actions"><button class="${state.liked[id]?"liked":""}" data-like="${id}">${state.liked[id]?"❤️":"👍"} إعجاب</button><button data-comment="${id}">💬 تعليق</button><button data-share="${id}">↗️ مشاركة</button></div></article>`}
function learning(){return `<div class="hero"><h1>🎓 مركز تعلم اللغات</h1><p>اختر لغة، حدد مستواك، وابدأ الدرس.</p><div class="stats"><div class="stat"><b>${state.progress}%</b>التقدم</div><div class="stat"><b>12</b>درس مكتمل</div><div class="stat"><b>240</b>نقطة</div></div></div>
<div class="card"><h2>اختر اللغة</h2><div class="lang-grid">${[["🇩🇪","Deutsch"],["🇬🇧","English"],["🇸🇦","العربية"],["🇫🇷","Français"],["🇪🇸","Español"],["🇹🇷","Türkçe"]].map(x=>`<button class="lang" data-language="${x[1]}"><div class="flag">${x[0]}</div><b>${x[1]}</b></button>`).join("")}</div></div>
<div class="card course"><div><h2>${state.language} — مستوى ${state.level}</h2><p>المفردات اليومية · القواعد · المحادثة</p><div class="progress"><div style="width:${state.progress}%"></div></div><p>${state.progress}% مكتمل</p><button class="primary" id="startLesson">متابعة الدرس</button></div><div class="lesson-box">📚<br><b>40</b><br><small>درس</small></div></div>
<div class="card"><h3>المستويات</h3><div class="chips">${["A1","A2","B1","B2","C1"].map(l=>`<button class="chip" data-level="${l}">${l}</button>`).join("")}</div></div>`}
function lesson(){let qs=[["gehen","Ich ___ zur Schule.",["gehe","geht","gehen","ging"],0],["sein","Wir ___ heute müde.",["ist","sind","bin","seid"],1],["haben","Ich ___ einen Bruder.",["habe","hat","haben","hast"],0]];let q=qs[state.lesson%qs.length];return `<div class="card"><button class="outline" onclick="go('learning')">← العودة</button><div class="lesson-box"><small>الدرس ${state.lesson+1} من 10</small><div class="word">${q[0]} <button class="speak" id="speak">🔊</button></div><p>${q[1]}</p><div class="options">${q[2].map((x,i)=>`<button class="option" data-answer="${i===q[3]}">${x}</button>`).join("")}</div><br><button class="primary" id="next">التالي</button></div></div>`}
function friends(){return `<div class="card"><h2>👥 الأصدقاء</h2><div class="people">${["Ali Mohammed","Sara Ahmed","Reem Khaled","Mohammed Hassan","Daniel Weber","Lina Saleh"].map(n=>`<div class="person"><div class="avatar small">${n[0]}</div><div><b>${n}</b><small>متصل الآن</small></div><button class="outline">إضافة</button></div>`).join("")}</div></div>`}
function groups(){return `<div class="card"><h2>🌐 المجموعات</h2><button class="primary" onclick="toast('تم إنشاء نموذج مجموعة جديد')">+ إنشاء مجموعة</button>${["تعلم اللغة الألمانية 🇩🇪","مبرمجون عرب في ألمانيا 💻","أصدقاء من مختلف الدول 🌍","Yezidi Language Community"].map((n,i)=>`<div class="group"><b>${n}</b><p>${120+i*55} عضو · نشطة اليوم</p><button class="outline">انضمام</button></div>`).join("")}</div>`}
function messages(){return `<div class="card"><h2>💬 الرسائل</h2><div class="message-list">${["Sara Ahmed","Ali Mohammed","Reem Khaled","Daniel Weber"].map((n,i)=>`<div class="message"><div class="avatar small">${n[0]}</div><div><b>${n}</b><small>${i===0?"هل تريد ممارسة الألمانية اليوم؟":"مرحباً، كيف حالك؟"}</small></div></div>`).join("")}</div></div>`}
function notifications(){return `<div class="card"><h2>🔔 الإشعارات</h2><div class="message-list">${["Sara أعجبت بمنشورك ❤️","تمت دعوتك إلى مجموعة تعلم اللغة الألمانية 🎓","لديك درس جديد متاح 📚","Ali أرسل لك طلب صداقة 👥"].map(x=>`<div class="message"><div class="avatar small">!</div><div><b>${x}</b><small>منذ قليل</small></div></div>`).join("")}</div></div>`}
function profile(){return `<div class="card"><div class="profile-cover"></div><div class="profile-info"><div class="avatar">S</div><h2>Shahwan Khalaf</h2><p>تواصل · تعلم · تطور 🌍</p><button class="primary">تعديل الملف الشخصي</button><div class="tabs"><button class="active">المنشورات</button><button>المعلومات</button><button>الصور</button></div></div></div>${post("p3","Shahwan Khalaf","أتعلم الألمانية وأشارك تقدمي مع أصدقائي.")}`}
function settings(){return `<div class="card"><h2>⚙️ الإعدادات</h2>${[["الحساب الشخصي",""],["الخصوصية",""],["الأمان",""],["لغة التطبيق","العربية"],["الإشعارات",""]].map(x=>`<div class="settings-row"><span>${x[0]}</span><small>${x[1]}</small></div>`).join("")}<div class="settings-row"><span>الوضع الليلي</span><button id="switch" class="switch ${document.body.classList.contains("dark")?"on":""}"></button></div></div>`}
const pages={home,learning,lesson,friends,groups,messages,notifications,profile,settings};
function bind(){
 document.querySelectorAll("[data-like]").forEach(b=>b.onclick=()=>{let id=b.dataset.like;state.liked[id]=!state.liked[id];render()});
 document.querySelectorAll("[data-comment]").forEach(b=>b.onclick=()=>toast("ميزة التعليقات جاهزة للربط بقاعدة البيانات"));
 document.querySelectorAll("[data-share]").forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText(location.href);toast("تم نسخ رابط المشاركة")});
 document.querySelectorAll("[data-language]").forEach(b=>b.onclick=()=>{state.language=b.dataset.language;toast("تم اختيار "+state.language);render()});
 document.querySelectorAll("[data-level]").forEach(b=>b.onclick=()=>{state.level=b.dataset.level;render()});
 const pub=document.querySelector("#publish"); if(pub)pub.onclick=()=>{let x=document.querySelector("#composer");if(x.value.trim()){toast("تم نشر المنشور");x.value=""}else toast("اكتب منشوراً أولاً")};
 const start=document.querySelector("#startLesson");if(start)start.onclick=()=>go("lesson");
 document.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".option").forEach(x=>x.disabled=true);b.classList.add(b.dataset.answer==="true"?"correct":"wrong");if(b.dataset.answer==="true"){state.progress=Math.min(100,state.progress+5);toast("إجابة صحيحة! +5 نقاط 🎉")}else toast("حاول مرة أخرى")});
 const next=document.querySelector("#next");if(next)next.onclick=()=>{state.lesson++;go("lesson")};
 const speak=document.querySelector("#speak");if(speak)speak.onclick=()=>{let u=new SpeechSynthesisUtterance(document.querySelector(".word").childNodes[0].textContent.trim());u.lang="de-DE";speechSynthesis.speak(u)};
 const sw=document.querySelector("#switch");if(sw)sw.onclick=()=>document.querySelector("#themeBtn").click();
}
function render(){document.body.classList.toggle("dark",state.theme==="dark"||localStorage.theme==="dark");app.innerHTML=(pages[state.page]||home)();nav();header();bind()}
window.addEventListener("hashchange",()=>{state.page=location.hash.slice(1)||"home";render()});
render();